- name: codename
  include_tasks: codename.yml
  #old: import_tasks

- name: python3-pip, curl
  become: yes
  apt:
    update_cache: yes
    pkg:
    - python3-pip
    - curl

- name: install with python 2
  include_tasks: python2.yml
  when: not python3

# Future
- name: install with python 3
  include_tasks: python3
  when: python3
