---
# https://itsfoss.com/externally-managed-environment/
- name: Install pipx
  ansible.builtin.apt:
    name: pipx
    state: present
  become: true

- name: Reset to load pipx
  ansible.builtin.meta: reset_connection

- name: Install cfv using pipx
  ansible.builtin.shell: pipx install cfv
  args:
    creates: "{{cfv_bin}}"

- name: link cfv into PATH
  ansible.builtin.file:
    src: "{{cfv_bin}}"
    dest: /usr/local/bin/cfv
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    state: link
  become: true